name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Run API unit tests
      run: dotnet test -c Release --verbosity normal --collect:"XPlat Code Coverage" --results-directory ./api-coverage

    - name: Copy API Code coverage
      run: cp api-coverage/**/coverage.cobertura.xml coverage.cobertura.xml

    - name: Code Coverage Summary Report
      uses: irongut/CodeCoverageSummary@v1.2.0
      with:
        filename: coverage.cobertura.xml
        badge: true
        fail_below_min: true
        format: markdown
        hide_branch_rate: false
        hide_complexity: true
        indicators: true
        output: both
        thresholds: '70 85'
    - name: Upload API code coverage
      uses: actions/upload-artifact@v2
      with:
        name: 'api code coverage'
        
#     - name: Test
#       run: dotnet test --no-build --verbosity normal /p:CollectCoverage=true /p:CoverletOutputFormat=opencover  
#     - name: Codecov
#       uses: codecov/codecov-action@v1
#       with:
#         directory: BuildReports/Coverage/
